[package]
name = "lib-util"
version = "0.1.0"
edition = "2021"

[dependencies]
digest = "0.11.1"

pin-project = "1.1.10"
tokio = "1.49.0"
futures = "0.3.31"
bytes = "1.10.1"
chacha20poly1305 = { version = "0.10", features = ["stream"] }
pin-project-lite = "0.2.16"
flate2 = "1.1.1"
base64ct = "1.7.3"
base64 = "0.22.1"
tokio-util = { version = "0.7.18", features = ["codec"] }
workspace-hackari = { version = "0.1", path = "../../workspace-hackari" }


[lints]
workspace = true
